# 프로미스

기존의 콜백 방식을 비동기화로 처리하기 한 객체이다. 

프로미스를 사용하려면  먼저 프로미스 객체를 생성 후 then과 catch를 통해서 코드를 구현한다.

~~~javascript
const condition = true;// true면 resolve, false면 reject
const promise = new Promise((resolve, reject) => {
    if (condition) {
        resolve('성공');
    }else {
        reject('실패');
    }
});

promise
.then((message) => {
    console.log(message); // 성공(resolve)한 경우 실행
})
.catch((err) => {
    console.log(err); // 실패(reject)한 경우 실행
})
~~~

위 코드를 보면 프로미스 객체 생성시 resolve와 reject를 받는 것을 볼 수 있다. 이 매개변수들은 함수이며  내부적으로 어떤 조건에 따라 호출이 된다. resolve는 성공을 의미하고 reject는 반려를 의미한다. 

프로미스 객체를 생성 후 객체를 사용할 때 then과 catch를 붙일 수 있는데 then은 resolve가 호출되면 실행되며 catch는 reject가 호출되면 실행한다.

다음은 콜백을 프로미스로 변경한 예이다. 

~~~javascript
// ES5
function findAndSaveUser(Users) {
    Users.findOne({},(err, user) => { //첫 번째 콜백
        if (err) {
            return console.error(err);
        }
        user.name = 'zero';
        user.save(err) => { // 두 번째 콜백
            if (err) {
                return console.error(error);
            }
            Users.findOne({ gender: 'm' }, (err, user) => { // 세 번째 콜백
                // 생략
            });
        }
    });
}

// ES6
function findAndSaveUser(Users) {
    Users.findOne({})
        .then((user) => {
            user.name = 'zero';
            return  user.save();
        })
        .then((user) => {
            return Users.findOne({ gender: 'm'});
        })
        .then((user) => {
            // 생략
        })
        .catch((err) => {
            console.error(err);
        });
}
~~~

위 코드에서 then은 순차적으로 실행되며 에러코드도 catch로 간단하게 구현됨을 볼 수 있다.  return 문을 이용해서 다음 then에 넘겨줄 수 있다. 모든 코드를 프로미스를 구현할 수 있는 것은 아니다. 위의 코드에서 find와 save가 내부적으로 프로미스 객체를 가지고 있어 가능한 것이다. 

여러 개의 프로미스를 한 번에 실행할 수 있는 방법이 있다. Promise.all을 활용하면 간단히 할 수 있다. 

~~~javascript
const proimse1 = Promise.resolve('성공1');
const proimse2 = Promise.resolve('성공2');
Promise.all(param)
 .then((result) => {
     console.log(result); // ['성공1', '성공2']
 })
 .catch((error) => {
     console.log(error);
 });
~~~







